/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.exercicioavaliativografico.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JPanel;

/**
 *
 * @author andre.lima
 */
public class GraphView extends javax.swing.JFrame {

    /**
     * Creates new form GraphPresernter
     */
    public GraphView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primaryPanel = new javax.swing.JPanel();
        graphPanel = new javax.swing.JPanel();
        graphsLabel = new javax.swing.JLabel();
        graphComboBox = new javax.swing.JComboBox<>();
        unDoBtn = new javax.swing.JButton();
        restoreBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        optionPanel = new javax.swing.JPanel();
        elementosLabel = new javax.swing.JLabel();
        tituloCheckBox = new javax.swing.JCheckBox();
        legendaCheckBox = new javax.swing.JCheckBox();
        tituloEixosCheckBox = new javax.swing.JCheckBox();
        rotuloPorcentagemCheckBox = new javax.swing.JCheckBox();
        rotuloValorCheckBox = new javax.swing.JCheckBox();
        rotuloValorPorcentagemCheckBox = new javax.swing.JCheckBox();
        corBarrasGrupoCheckBox = new javax.swing.JCheckBox();
        gradeCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grafico");

        graphPanel.setLayout(new javax.swing.BoxLayout(graphPanel, javax.swing.BoxLayout.LINE_AXIS));

        graphsLabel.setText("Gráficos padão");

        graphComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        unDoBtn.setText("Desfazer");

        restoreBtn.setText("Restaurar padrão");

        exitBtn.setText("Fechar");

        optionPanel.setBackground(new java.awt.Color(255, 255, 255));

        elementosLabel.setText("Elementos gráficos");

        tituloCheckBox.setText("Titulo");

        legendaCheckBox.setText("Legenda");

        tituloEixosCheckBox.setText("Titulo dos eixos");
        tituloEixosCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloEixosCheckBoxActionPerformed(evt);
            }
        });

        rotuloPorcentagemCheckBox.setText("Rótulo de Dados (%)");

        rotuloValorCheckBox.setText("Rótulo de Dados - Valor");

        rotuloValorPorcentagemCheckBox.setText("Rótulo de Dados - Valor (%)");
        rotuloValorPorcentagemCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotuloValorPorcentagemCheckBoxActionPerformed(evt);
            }
        });

        corBarrasGrupoCheckBox.setText("Cor das Barras (por grupo)");

        gradeCheckBox.setText("Grade");

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(legendaCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elementosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloEixosCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rotuloPorcentagemCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rotuloValorPorcentagemCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(corBarrasGrupoCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gradeCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rotuloValorCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(elementosLabel)
                .addGap(31, 31, 31)
                .addComponent(tituloCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(legendaCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloEixosCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rotuloPorcentagemCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rotuloValorCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rotuloValorPorcentagemCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corBarrasGrupoCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradeCheckBox)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout primaryPanelLayout = new javax.swing.GroupLayout(primaryPanel);
        primaryPanel.setLayout(primaryPanelLayout);
        primaryPanelLayout.setHorizontalGroup(
            primaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primaryPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(primaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, primaryPanelLayout.createSequentialGroup()
                        .addComponent(unDoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(restoreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, primaryPanelLayout.createSequentialGroup()
                        .addComponent(graphsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(graphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(primaryPanelLayout.createSequentialGroup()
                        .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        primaryPanelLayout.setVerticalGroup(
            primaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(primaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(graphsLabel)
                    .addComponent(graphComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(primaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 22, Short.MAX_VALUE)
                .addGroup(primaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn)
                    .addComponent(restoreBtn)
                    .addComponent(unDoBtn))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(primaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(primaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tituloEixosCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloEixosCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloEixosCheckBoxActionPerformed

    private void rotuloValorPorcentagemCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotuloValorPorcentagemCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rotuloValorPorcentagemCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphView().setVisible(true);
            }
        });
    }

/*
    public JCheckBox getCorBarrasCheckBox() {
        return corBarrasCheckBox;
    }
*/

    public JCheckBox getCorBarrasGrupoCheckBox() {
        return corBarrasGrupoCheckBox;
    }

    public JButton getExitBtn() {
        return exitBtn;
    }

    public JCheckBox getGradeCheckBox() {
        return gradeCheckBox;
    }

    public void setGraphPanel(JPanel graphPanel) {
        this.graphPanel = graphPanel;
    }

    public JPanel getPrimaryPanel() {
        return primaryPanel;
    }

    public void setPrimaryPanel(JPanel primaryPanel) {
        this.primaryPanel = primaryPanel;
    }
    
    

    public void setRotuloPorcentagemCheckBox(JCheckBox rotuloPorcentagemCheckBox) {
        this.rotuloPorcentagemCheckBox = rotuloPorcentagemCheckBox;
    }
    

    public JComboBox<String> getGraphComboBox() {
        return graphComboBox;
    }

    public JPanel getGraphPanel() {
        return graphPanel;
    }

    public JCheckBox getLegendaCheckBox() {
        return legendaCheckBox;
    }

    public JPanel getOptionPanel() {
        return optionPanel;
    }

    public JButton getRestoreBtn() {
        return restoreBtn;
    }

    public JCheckBox getRotuloPorcentagemCheckBox() {
        return rotuloPorcentagemCheckBox;
    }

    public JCheckBox getRotuloValorCheckBox() {
        return rotuloValorCheckBox;
    }

    public JCheckBox getRotuloValorPorcentagemCheckBox() {
        return rotuloValorPorcentagemCheckBox;
    }

    public JCheckBox getTituloCheckBox() {
        return tituloCheckBox;
    }

    public JCheckBox getTituloEixosCheckBox() {
        return tituloEixosCheckBox;
    }

    public JButton getUnDoBtn() {
        return unDoBtn;
    }

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox corBarrasGrupoCheckBox;
    private javax.swing.JLabel elementosLabel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JCheckBox gradeCheckBox;
    private javax.swing.JComboBox<String> graphComboBox;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JLabel graphsLabel;
    private javax.swing.JCheckBox legendaCheckBox;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPanel primaryPanel;
    private javax.swing.JButton restoreBtn;
    private javax.swing.JCheckBox rotuloPorcentagemCheckBox;
    private javax.swing.JCheckBox rotuloValorCheckBox;
    private javax.swing.JCheckBox rotuloValorPorcentagemCheckBox;
    private javax.swing.JCheckBox tituloCheckBox;
    private javax.swing.JCheckBox tituloEixosCheckBox;
    private javax.swing.JButton unDoBtn;
    // End of variables declaration//GEN-END:variables
}
